In [15]:
#import libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_samples, silhouette_score

In [4]:
#imporiting csv into a dataframe
df = pd.read_csv("als_data.csv")

In [5]:
df

,ID,Age_mean,Albumin_max,Albumin_median,Albumin_min,Albumin_range,ALSFRS_slope,ALSFRS_Total_max,ALSFRS_Total_median,ALSFRS_Total_min,...,Sodium_min,Sodium_range,SubjectID,trunk_max,trunk_median,trunk_min,trunk_range,Urine.Ph_max,Urine.Ph_median,Urine.Ph_min
0,1,65,57.0,40.5,38.0,0.066202,-0.965608,30,28.0,22,...,143.0,0.017422,533,8,7.0,7,0.002646,6.00,6.0,6.0
1,2,48,45.0,41.0,39.0,0.010453,-0.921717,37,33.0,21,...,136.0,0.010453,649,8,7.0,5,0.005386,7.00,5.0,5.0
2,3,38,50.0,47.0,45.0,0.008929,-0.914787,24,14.0,10,...,140.0,0.008929,1234,5,0.0,0,0.008929,6.00,5.0,5.0
3,4,63,47.0,44.0,41.0,0.012111,-0.598361,30,29.0,24,...,138.0,0.012469,2492,5,5.0,3,0.004988,7.00,6.0,5.0
4,5,63,47.0,45.5,42.0,0.008292,-0.444039,32,27.5,20,...,138.0,0.008292,2956,6,4.0,1,0.008489,6.00,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2218,2419,33,50.0,49.0,45.0,0.008772,-0.239501,35,32.5,30,...,136.0,0.014035,997136,7,5.0,5,0.003643,7.00,6.0,5.0
2219,2420,61,47.0,45.0,42.0,0.009074,-0.388711,31,26.0,17,...,141.0,0.009074,998047,5,4.0,3,0.003630,7.41,5.5,5.0
2220,2421,47,46.0,44.0,41.0,0.012111,-0.108631,26,23.0,20,...,135.0,0.013123,998773,5,4.0,4,0.001825,9.00,6.0,5.0
2221,2422,37,49.0,44.0,39.0,0.017857,-0.855880,34,29.5,21,...,136.0,0.007143,998908,8,4.5,2,0.010714,6.00,5.0,5.0
2222,2424,48,48.0,45.0,40.0,0.018476,-2.050562,37,34.0,11,...,137.0,0.018476,999482,8,8.0,1,0.016129,5.00,5.0,5.0

Remove any data that is not relevant to the patient’s ALS condition.

In [8]:
#removing the id column
df = df.drop('ID', axis=1)
df

,Age_mean,Albumin_max,Albumin_median,Albumin_min,Albumin_range,ALSFRS_slope,ALSFRS_Total_max,ALSFRS_Total_median,ALSFRS_Total_min,ALSFRS_Total_range,...,Sodium_min,Sodium_range,SubjectID,trunk_max,trunk_median,trunk_min,trunk_range,Urine.Ph_max,Urine.Ph_median,Urine.Ph_min
0,65,57.0,40.5,38.0,0.066202,-0.965608,30,28.0,22,0.021164,...,143.0,0.017422,533,8,7.0,7,0.002646,6.00,6.0,6.0
1,48,45.0,41.0,39.0,0.010453,-0.921717,37,33.0,21,0.028725,...,136.0,0.010453,649,8,7.0,5,0.005386,7.00,5.0,5.0
2,38,50.0,47.0,45.0,0.008929,-0.914787,24,14.0,10,0.025000,...,140.0,0.008929,1234,5,0.0,0,0.008929,6.00,5.0,5.0
3,63,47.0,44.0,41.0,0.012111,-0.598361,30,29.0,24,0.014963,...,138.0,0.012469,2492,5,5.0,3,0.004988,7.00,6.0,5.0
4,63,47.0,45.5,42.0,0.008292,-0.444039,32,27.5,20,0.020374,...,138.0,0.008292,2956,6,4.0,1,0.008489,6.00,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2218,33,50.0,49.0,45.0,0.008772,-0.239501,35,32.5,30,0.009107,...,136.0,0.014035,997136,7,5.0,5,0.003643,7.00,6.0,5.0
2219,61,47.0,45.0,42.0,0.009074,-0.388711,31,26.0,17,0.025408,...,141.0,0.009074,998047,5,4.0,3,0.003630,7.41,5.5,5.0
2220,47,46.0,44.0,41.0,0.012111,-0.108631,26,23.0,20,0.010949,...,135.0,0.013123,998773,5,4.0,4,0.001825,9.00,6.0,5.0
2221,37,49.0,44.0,39.0,0.017857,-0.855880,34,29.5,21,0.023214,...,136.0,0.007143,998908,8,4.5,2,0.010714,6.00,5.0,5.0
2222,48,48.0,45.0,40.0,0.018476,-2.050562,37,34.0,11,0.059908,...,137.0,0.018476,999482,8,8.0,1,0.016129,5.00,5.0,5.0

Apply a standard scalar to the data.

In [12]:
#assigning standarscaler
scaler = StandardScaler()

In [14]:
#fitting scaler
df_fit = scaler.fit_transform(df)
df_fit

array([[ 0.91713698,  3.08941722, -1.30078105, ..., -0.88037551,
         0.46305355,  1.86853157],
       [-0.57487867, -0.62201561, -1.11240084, ...,  0.1926645 ,
        -1.13720768, -0.41915124],
       [-1.45253494,  0.92441474,  1.14816173, ..., -0.88037551,
        -1.13720768, -0.41915124],
       ...,
       [-0.6626443 , -0.31272954,  0.01788044, ...,  2.33874452,
         0.46305355, -0.41915124],
       [-1.54030057,  0.61512867,  0.01788044, ..., -0.88037551,
        -1.13720768, -0.41915124],
       [-0.57487867,  0.3058426 ,  0.39464087, ..., -1.95341552,
        -1.13720768, -0.41915124]])

Create a plot of the cluster silhouette score versus the number of clusters in a K-means cluster.

In [16]:
#number of clusters
range_n_clusters = [2, 3, 4, 5, 6]

In [17]:
#empty list
silhouette_score = []

In [18]:
for cluster in range_n_clusters:
    
    # build k-means model
    kmeans = KMeans(n_clusters = cluster)
    kmeans.fit(df_fit)
    cluster_labels = kmeans.labels_
    
    # append the score into the empty list
    score.append(silhouette_score(df_fit, cluster_labels))

NameError: name 'KMeans' is not defined

In [ ]:

for num_clusters in range_n_clusters:
 
 # initialize k-means model
 kmeans = KMeans(n_clusters=num_clusters)
 kmeans.fit(df_fit)
 cluster_labels = kmeans.labels_
 
 # silhouette score
 silhouette_avg.append(silhouette_score(data_frame, cluster_labels))plt.plot(range_n_clusters,silhouette_avg,’bx-’)
plt.xlabel(‘Values of K’) 
plt.ylabel(‘Silhouette score’) 
plt.title(‘Silhouette analysis For Optimal k’)
plt.show()

In [ ]:
# define a n number of clusters
n_number_clusters = [2, 3,4,5]

# intialize a empty list for adding all the score
score = []

for clustr in n_number_clusters:
    
    # build k-means model on different set of k values
    kmeans = KMeans(n_clusters = clustr)
    kmeans.fit(X)
    cluster_labels = kmeans.labels_
    
    # append the score into the empty list
    score.append(silhouette_score(X, cluster_labels))
    
# plot the graph    
plt.plot(n_number_clusters,score)
plt.show()

Use the plot created in (3) to choose on optimal number of clusters for K-means. Justify your choice.

Fit a K-means model to the data with the optimal number of clusters chosen in part (4).

Fit a PCA transformation with two features to the scaled data.

Make a scatterplot the PCA transformed data coloring each point by its cluster value.

Summarize your results and make a conclusion.